### ISSUE TITLE
Missing model_src.search_space.nb101

### ISSUE THREAD

**Issue by akhauriyash** [Ascend-Research/GENNAPE#3]
Hello,

Are there plans to open source model_src.search_space.nb101? 

Thanks!

**Comment by kgmills** [comment]
If you have import errors related to `model_src.search_space`, they likely stem from `model_src/predictor/gpi_family_data_manager.py` because you haven't downloaded the CG datafiles from the [Google Drive link](https://drive.google.com/drive/folders/1nTj8g6XbIU_PYvOBaXjylBHmgo-3okra) or haven't placed them in the proper folders per the instructions in `README.md`:

- `.json` files should be copied into `data/`, alongside `tf_primitive_ops_simplified.txt`
- `.pkl` files should be copied into `cache/` (you will need to mkdir this directory). 

Please update me if this is the case, and I will update the code to provide further clarification.
If this is not the case, please provide further details to assist in debugging the issue.

**Comment by akhauriyash** [comment]
Hello,

To clarify, after further inspection, I believe the current code only supports the CGs that your team has generated (50k NB101, 4.1k NB201, 10k NB301, 8.2k PN, 7.5k OFA-MBv3, 10k OFA-RN, 4.6k HiAML, 580 Inception and 6..9k Two-Path models). 

```
            if not os.path.isfile(cache_file):
                self.log_f("Building cache for {}".format(f))
                self._build_cache(f, cache_file)
```
The GENNAPE code can indeed support building the cache file provided the *src_data.pkl (I am not aware of what it would take to generate the *src_data.pkl in the first place), and I think it would be very valuable to have the model_src.search_space code.

It is great that the cache file has been provided and is super useful, but I do not think it is possible to generate the CGs for 'new' architectures aside from the ones that are provided. It is my understanding that providing the model_src.search_space code would enable us to generate our own architecture CGs for training with the search spaces mentioned above. 

Thank you!

**Comment by kgmills** [comment]
We have open-sourced the code for NAS-Bench-{101, 201, 301} and the OFA search space families. The file `gen_demo_caches.py` iterates over the caches for these families and re-generates them (including their CGs), but the code involved can be used to generate additional CGs for architectures we did not sample.

I have modified some of the code in `/model_src/predictor/` to remove dependencies on the `*src_data.pkl` files, as their contents are actually contained within the already-provided `gpi_*_comp_graph_cache.pkl` files. That is, if you open a cache:

```
import pickle

with open("cache/gpi_nb101_comp_graph_cache.pkl", "rb") as f:
	cgs = pickle.load(f)
```

You will get a list whose length is the number of CGs in the cache. Each item is a dictionary corresponding to a specific architecture, e.g.,
![original_config_example](https://github.com/Ascend-Research/GENNAPE/assets/22038637/501f4265-b697-4e79-8609-56bb785506ab)


`original config` is the relevant blueprint needed to re-construct the CG using the `/model_src/search_space/` code.
